travis:
  secure:
    BINSTAR_TOKEN: XFC/O+jwONZ/vXKs89aL5DMESl+ehd6Ty21PJ0CAS3ccfkZSaGu34+bQY6h7PqCPJMObEYr9P54+ROawh7YT87Kl85y+QvFGjasXpyDLslr+kKhAvkpuwPwUYNsspkzj1Nxr5s6jQkIUDj3NnDT2yyrcKOZeXJqciwRYnb3vgEipE0wR/MM1EfFM8y2J8ebOpsdSR1KkO8DOsPThccfA0awCERoTezSbkSW1CLh7Vb7ZDdREf0ydxg1jwME4UGroVQgZJG++JoAZJVm9pCqiOenIit0IzlWhaIxHcma0WXh1z3UbZjN6iqxulW7nY/u0eEGUMqehiBy5K/seVtK16brplrsvvuPgxhkKoLKZ7DUg0wH+LQc8z72L13rosRVoAMvEUg7Z1I+N5Tct5Ux2epjyxCW016uwSo0ZBS7mMzctSgZq0poz88R7DhTwGMNeMNXRj/Uvs+fukUi+TBxF63Db6tIXO9D9s0dE6+4a6Cdm9ffKYgV8cL467zUtVI2/d+KTePHFQvdnJHyxVDuqBb0F7FmvL1Cc0n75y7k9odt2RPM2v2Eprn/nNbWAlKQbArdNupw1fXwE/5yiqDNm1hrEuQLN9JezGbHh7RNAor0KswL8oPBOxaIJAkUjUfApaQKbhdDH3ZBW1+TVwh9VKk/5wLktFQX1RMpd/F8jzbM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
