appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: LkKlK75rB9tjXgR/1t0rXyuzvHwCWeoo5bxDvR0B9mvGmJpmwzOBEBBht/g8yuOsmdtMAr0RudZ0HdSs7dmklJmAtxVXsBKfCxtgKccCBWyn0QRCi04lpn+n3tLEOo0M53OScS4nTr+1O2iRytFtQUHSutWZP3BDvQfinDAOaPXI6RLqGHAyXdaTtJmANaFQS7wEpXxaI0D3KSP7eQCiceB7w7rOjvbCNAUypcGW4xI2kx4knlLNZJb4I4Hff92lKNpb+G2nVKFwI9oPK8j29mjjG48olYcsR16Y4yp2paDhYmkQFN7GOahSDXDp9lOaY1arMLm26CxWXe8vS1SNKgcQfixevu7M/jdmQBtAVgHvhLS0hZUvceo3+dqZXIWjo2RTBBvoAQtJY3UrMAjzPa9YT4N0iE19RWGLyOOh05F1jR2XS8oNonXyNSiqD1F4MCJCVEtkz9Iks/Dfy5FD8YJAQzX/4aUcvYRKmLc9agubYIX3/MufVX54efQ1B1c6ja/UMlJLJJ549hlG+W1t+xtG3RA7wxnqz+NhV4VDJoVC2Uv0y1yIOVDIPZqix02u9LMZ448IUhYAdq/Rcm9BGcUyhOtraEVs/f5EtvVcBa67n9tzdGXDzyJiZg5HzL9m4o3Qr/n9UP5EXrOJnjN8qRtOlqgXdtqvC40IXhmXJoM=}
conda_forge_output_validation: true
